branches:
    only:
        - master

language: perl6

perl6:
    - latest

# sudo required for libxxhash installation
sudo: required

env:
    - PATH=~/.rakudobrew/bin:$PATH

before_install:
    # install libxxhash into /usr/lib/libxxhash.so
    - curl https://codeload.github.com/Cyan4973/{xxHash}/{tar.gz}/{v0.7.4} -o "#1-#3.#2"
    - tar xvzf xxHash-v0.7.4.tar.gz
    - cd xxHash-0.7.4
    - make lib
    - sudo make PREFIX="/usr" install
    - cd $TRAVIS_BUILD_DIR

install:
    - cd $TRAVIS_BUILD_DIR
    - rakudobrew build zef
    - zef build .
    - zef --deps-only --/test install .
